- name: add mongodb key
  apt_key:
    #keyserver: hkp://keyserver.ubuntu.com:80
    keyserver: "{{ mongodb_apt_keyserver }}"
    #id: 0C49F3730359A14518585931BC711F9BA15703C6
    #id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    #id: 7F0CEB10
    #id: EA312927
    id: "{{ mongodb_apt_gpg_key }}"
  when: >
        ansible_distribution == "Ubuntu"

- name: install mongodb repository
  apt_repository:
    #repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/{{mongodb_version}} multiverse"
    repo: "{{ mongodb_ubuntu_apt_repo }}"
    state: "present"
    update_cache: "yes"
  when: >
        ansible_distribution == "Ubuntu"


- name: install mongodb
  apt:
    name: "mongodb-org"
    state: "present"
    update_cache: yes
  when: >
        ansible_distribution == "Ubuntu"

- name: enable and start mongod service
  service:
    name: "mongod"
    enabled: "yes"
    state: started
